server/forms/document-add.json, server/middleware/validation.js, server/services/form.js, server/services/list.js
This commit adds whitelisting of file extensions.
SecurityTheatre++
=> HOCS-226 Add extension whitelisting

server/forms/bulk-create.json, server/forms/document-add.json, server/forms/index.js, server/middleware/validation.js, server/routes/action/index.js, server/routes/case/index.js, server/services/action.js, server/services/form.js, src/shared/common/forms/form.jsx, src/shared/pages/main.jsx
today I learnt what `git cherry-pick` actually did
=> Add form for bulk uploading cases

server/config.js, server/libs/request.js, server/routes/case/index.js, src/shared/common/components/workstack.jsx, src/shared/pages/main.jsx
Initial implementation of a work-stack component for development purposes
Known issues: 
- currently does not support ssr
=> Implement basic workstack

server/layout/__tests__/__snapshots__/html.spec.js.snap, server/layout/html.js, server/middleware/stage.js, server/services/__tests__/form.spec.js, server/services/__tests__/list.spec.js, server/services/form.js, src/shared/common/forms/composite/__tests__/__snapshots__/entity-manager.spec.jsx.snap, src/shared/layouts/components/__tests__/__snapshots__/header.spec.js.snap, src/shared/layouts/components/header.jsx, src/shared/pages/__tests__/__snapshots__/dashboard.spec.jsx.snap, src/shared/pages/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/pages/main.jsx
Move links from main page to header
And move towards SPA design goal
=> Move links from main page to header

docker/docker-compose.yml, docker/keycloak/local-realm.json, docker/scripts/infrastructure.sh, server/middleware/stage.js, server/routes/index.js, server/services/action.js, server/services/list.js, server/services/lists/index.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/workstack-allocate.jsx, src/shared/common/components/workstack.jsx, src/shared/common/forms/composite/__tests__/__snapshots__/entity-manager.spec.jsx.snap, src/shared/pages/__tests__/__snapshots__/dashboard.spec.jsx.snap, src/shared/pages/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/pages/workstack.jsx, src/styles/app.scss
Move frontend calls from workflow to casework as workflow just calls casework directly anyway.
=> Nm repoint topic casework

docker/docker-compose.yml, docker/keycloak/local-realm.json, docker/scripts/infrastructure.sh, server/middleware/stage.js, server/routes/index.js, server/services/list.js, server/services/lists/index.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/workstack-allocate.jsx, src/shared/common/components/workstack.jsx, src/shared/common/forms/composite/__tests__/__snapshots__/entity-manager.spec.jsx.snap, src/shared/pages/__tests__/__snapshots__/dashboard.spec.jsx.snap, src/shared/pages/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/pages/workstack.jsx, src/styles/app.scss
WIP: repoint the new workstacks code to casework URL instead of workflow.
=> Nm update urls

server/services/action.js, server/services/forms/form-builder.js, server/services/forms/schemas/dashboard-search.js, src/shared/common/forms/panel.jsx, src/shared/contexts/__tests__/application.spec.js, src/shared/pages/action.jsx, src/shared/pages/case.jsx, src/shared/pages/dashboard.jsx, src/shared/pages/form-enabled.jsx, src/styles/app.scss
I need help doing Jest -u on this.
=> link to newly created case from confirmation screen

docker/docker-compose.yml, server/lists/adapters/case-notes.js, server/services/forms/schemas/add-member-details.js, src/shared/common/forms/__tests__/form-repository.spec.js, src/shared/common/forms/form-repository.jsx, src/shared/common/forms/hidden.jsx
add new timeline events for stage completed, created
=> Add correspondent external key

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap, server/services/action.js, src/shared/common/forms/composite/__tests__/__snapshots__/entity-manager.spec.jsx.snap, src/shared/pages/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/router/routes/index.js
=> show preview on add member loop

docker/docker-compose.yml, server/config.js
Updating port for workflow service running locally
=> Making sure that keycloak version is consistent (5.0.0)

.drone.yml
Reverting CI Drone changes (broken for the moment)
=> Reverting the drone changes as they

.eslintrc.js, server/services/form.js
added a custom url used by the submit button when a case is in the unallocated state, so that it posts to the team allocation url.
=> HOCS-992-Allocate-User-Error added a submission url for unallocated cases

server/lists/adapters/__tests__/__snapshots__/stringSorted.spec.js.snap, server/lists/adapters/__tests__/stringSorted.spec.js, server/lists/adapters/stringSorted.js, server/lists/index.js
Removed historic list. Pointed current list at new endpoint. Merge to WCS.
=> Provide list of countries.

server/middleware/__tests__/process.spec.js, server/middleware/process.js, src/shared/common/forms/__tests__/__snapshots__/checkbox-group.spec.js.snap, src/shared/common/forms/__tests__/checkbox-group.spec.js, src/shared/common/forms/__tests__/form-repository.spec.js, src/shared/common/forms/checkbox-group.jsx, src/shared/common/forms/form-repository.jsx
Added checkboxes to dynamic form. Some reformatting to make style police happy. Merge to WCS.
=> Change registration form fields to match mock. Add checkboxes.

server/middleware/__tests__/validation.spec.js, server/middleware/validation.js
Numeric validation. Merge to WCS.
=> HOCS-1245 : numeric validation

server/lists/adapters/__tests__/__snapshots__/case-summary.spec.js.snap, server/lists/adapters/__tests__/case-summary.spec.js, server/lists/adapters/case-summary.js, src/shared/common/components/stage-summary.jsx
Update summary tab. Merge to WCS.
=> HOCS-1318 : update summary tab

server/__tests__/tenantConfig.spec.js, server/config.js, server/middleware/render.js, server/tenantConfig.js, src/shared/layouts/components/header.jsx
Also including changes for
HOCS-1237 - Remove "bulk" case link from header
=> HOCS-1169 - Customise product title

src/styles/app.scss
=> HOCS-1367 - Record claimant gender

server/lists/adapters/__tests__/__snapshots__/countrySort.spec.js.snap, server/lists/adapters/__tests__/countrySort.spec.js, server/lists/adapters/countrySort.js, server/lists/index.js
Display UK at top of dropdown list of countries. Merge to WCS.
=> HOCS-1371 : display UK at top of dropdown list of countries

src/shared/common/forms/text.jsx, src/shared/pages/dashboard.jsx
Calculate total Awarded and Paid amounts. Merge to WCS.
=> HOCS-1402 : calculate total amounts, update totals between form submits

server/middleware/__tests__/validation.spec.js, server/middleware/validation.js
Validate components within expandable checkbox.
=> HOCS-1424 : validate components within expandable checkbox

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
Add brought forward date, handle no date value (was displaying "NaN/NaN/NaN").
=> HOCS-1298 : add brought forward date, handle no date value

server/middleware/__tests__/searchHandler.spec.js, server/middleware/searchHandler.js
The search flag for active cases only wasn't being correctly set.
=> HOCS-1445 : search active cases only returns active cases

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
Fix: brought forward date when null displays blank in workstack.
=> HOCS-1624 : bf date when null displays blank

server/services/forms/index.js
=> UKVI2-HOCS-1630 : high level skeleton

server/lists/index.js
List for correspondence goes to Casework. Merge to UKVI2.
=> UKVI2 HOCS-1589 : add correspondent

server/services/__tests__/action.spec.js, server/services/action.js
Default file upload during case creation to first document tag in list (parity with previous functionality).
=> HOCS-1551 : make document tags case type specific

server/lists/adapters/__tests__/documents.spec.js, server/lists/adapters/documents.js
Get list of document tags comes from response rather than config.
=> HOCS-1551 : make document tags case type specific, fix

src/shared/common/forms/dropdown.jsx
(temporary hotfix as this casuses entire search and team workstack to go blank)
=> HOCS-1648 - UKVI Correspondence Business Unit

src/shared/common/forms/radio-group.jsx
radio group handles selected value becoming invalid when condition field changes value, code review to return null when possible
=> HOCS-1651 : response channels

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap, server/lists/adapters/case-notes.js, src/shared/common/components/__tests__/__snapshots__/case-note.spec.jsx.snap, src/shared/common/components/case-note.jsx, src/shared/common/components/case-notes.jsx
HOCS-1720 - Phone call sumary case note gets wrong prefix
=> HOCS-1721 - Rejection note prefix rewording

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap, server/lists/adapters/__tests__/case-notes.spec.js, server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
=> HOCS-1742 : cases at Draft Escalate can be closed

src/shared/common/components/workstack.jsx, src/styles/app.scss
New column render to highlight row in red when date value is before the row's deadline warning date.
=> HOCS-1568 : highlight in red any case approaching OOSS

server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
- Added mappings for new case note (REQUEST_CONTRIBUTION)
=> HOCS-1806 - UKVI Request Contribution

src/shared/common/components/side-bar.jsx
- suppressed people's tab for wcs cases (logic based on caseId)
=> HOCS-1819 - Hide People's tab on WCS system

src/shared/common/forms/accordion.jsx, src/shared/common/forms/form-repository.jsx
The form repository now passes the "page" object to the Accordion component.
=> HOCS-1742 : support flow-direction-link rendered within Accordion

src/shared/router/routes/index.js
Display sidebar when adding correspondent.
=> HOCS-1844 : display sidebar when adding correspondent, fix

server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
Mapping 'WITHDRAW' case note type
=> HOCS-1816 - Withdraw a WCS claim

src/styles/app.scss
Applied responsive css to three entity list components: 1.Correspondents, 2.DraftDocuments, 3.Topics.
=> HOCS-1838: Apply responsive css to specific components.

server/services/forms/schemas/manage-people.js
Change the `hideSidebar` flag to `false` to show the sidebar with the manage-people form.
=> HOCS-1844: Add sidebar to manage-people form.

src/shared/router/routes/index.js
Added a new route for the manage documents path, with the `hasSidebar` flag set to false.
=> HOCS-1851: Add new route for manage documents path.

server/middleware/validation.js
- added logic for skipping validation when validationSuppressors are specified
- Date field is always validated regardless of the validation suppression config
=> HOCS-1862 - Ability to suppress validation on certain actions

server/middleware/__tests__/searchHandler.spec.js, server/middleware/searchHandler.js
- added wiring for CampaignType search
=> HOCS-1874 - UKVI Campaign - Search

server/lists/adapters/workstacks.js
- removed test code committed by mistake (testing when campaign did
not exist)
=> HOCS-1876 - UKVI Campaign - Workstack View

src/shared/common/forms/composite/entity-list.jsx
Entity list UX of second visit matches first visit.
=> HOCS-1826 : QA Response can modify primary draft documents, fix

server/lists/adapters/workstacks.js, server/lists/index.js, server/middleware/__tests__/searchHandler.spec.js, server/middleware/searchHandler.js, server/middleware/validation.js, src/shared/common/forms/form-repository.jsx
- added list mappings for MIN Sign Off teams
- added search mappings for MinSignOffTeam
- added ability to hide fields based on data properties (reactive)
- skipped validation on fields that are hidden
=> HOCS-1917 - UKVI Home Sec Cases

server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
Add the title and pass the note for notes that come through with case type of SEND_TO_WORKFLOW_MANAGER. Add flag for it to be classed as a case note on the timeline item.
=> HOCS-1960: add case note for send to workflow manager

server/middleware/__tests__/searchHandler.spec.js, server/middleware/searchHandler.js
New text box to search for cases by full name of correspondents who are not MPs
=> HOCS-1997 : new text box to search for cases by fullname

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap
Fix a broken test missed by previous branch change.
=> HOCS-2040: fix broken test

package-lock.json, server/lists/adapters/case-notes.js
Additions for mandatory case notes when converting a case from ministerial to official or vice versa.
=> added two new case note type adaptors

server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
Case notes added as part of a case conversion will now be visible in the timeline.
=> made case notes visible for case conversions

server/services/form.js
Reverts UKHomeOffice/hocs-frontend#540
Although this fixed this issue, other capabilities were influenced negatively, so need to relook at solution.
=> Revert "HOCS-2015 UKVI Reference Type Change"

server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
Added a new case note type for the close case by telephone events.
=> HOCS-2019 : add new case note type for close case by telephone.

server/layout/__tests__/__snapshots__/html.spec.js.snap, server/layout/html.js, server/middleware/__tests__/process.spec.js, server/middleware/__tests__/validation.spec.js, server/middleware/process.js, server/middleware/validation.js, src/shared/common/forms/__tests__/__snapshots__/radio-group.spec.js.snap, src/shared/common/forms/__tests__/form-repository.spec.js, src/shared/common/forms/__tests__/radio-group.spec.js, src/shared/common/forms/form-repository.jsx, src/shared/common/forms/radio-group.jsx
This PR contains the functionality to input MPAM missalocations data the data input stage.
=> HOCS-2136: Transfer to OGD at MPAM Creation stage

docker/db_setup/workflow.sql, docker/docker-compose.yml
Tiny change to save manual step to create schema.
=> create 'workflow' schema

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap, server/lists/adapters/__tests__/workstacks.spec.js, server/middleware/__tests__/somu.spec.js, server/middleware/somu.js, server/services/form.js, server/services/forms/schemas/__tests__/index.spec.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/forms/composite/__tests__/__snapshots__/somu-list.spec.jsx.snap, src/shared/common/forms/composite/__tests__/somu-list.spec.jsx, src/shared/common/forms/composite/somu-list.jsx, src/styles/app.scss
1. Extends unit test coverage.
2. Address comments from https://github.com/UKHomeOffice/hocs-frontend/pull/558
=> HOCS-2299: add multiple contribution unit tests

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap, server/lists/adapters/__tests__/workstacks.spec.js, server/lists/adapters/workstacks.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
This PR reintroduces the DueDate check to the workstack component and adapter.
This fixes MC removing DueDate from showing for Dispatch Follow up Cases.
=> HOCS-2322: Reintroduce DueDate to Workstack

.drone.yml, package.json, server/lists/adapters/__tests__/workstacks.spec.js, server/services/__tests__/form.spec.js, src/shared/common/forms/hidden.jsx, src/shared/layouts/error.jsx
This pull request contains the following changes: 
- Fix linting within package.json to now include .jsx files.
- Fix linting issues within the codebase.
- Add drone step that does linting checks on any push.
=> HOCS-2381: Fix linting and add to build steps 

src/shared/common/forms/radio-group.jsx
* pull conditional textbox value from state when it is selected
* set conditional textbox value instead of textbox defaultValue when it is selected
=> hocs-2392-conditional-validation-errors

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap, server/lists/adapters/__tests__/case-notes.spec.js, server/lists/adapters/case-notes.js, src/shared/common/components/case-notes.jsx
=> HOCS-2225 : DCU, Private Office change topic

server/lists/index.js, server/middleware/__tests__/workstack.spec.js, server/middleware/workstack.js, server/routes/api/workstack.js, server/routes/page.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx, src/shared/common/forms/submit.jsx, src/shared/pages/workstack.jsx
* add handler to differentiate between submit buttons
* add move team option
* invoke casework api to move cases between teams
=> HOCS-2367-WCS_Option for bulk transfer of cases

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
* Do not add sort link to header if noRef strategy specified
=> HOCS-2546 Disable sorting in DCU correspondent/reference field

server/lists/adapters/workstacks.js
* Add new screens to workstack contributions arrays
=> HOCS-2311-Request-contribution-at-escalated-stage

server/lists/index.js
New static list.
Merge to epic.
=> HOCS-2648 : CCH workflow

server/services/forms/index.js
HOCS-2548 - For creating a new FOI case a new FOI label is added to the create form
=> HOCS-2548 - label for FOI cases

server/lists/index.js
This ticket implements the FOI case types required for the drop down list used in the data input stage.
=> HOCS-2519 add foi types for drop down

src/shared/common/components/workstack.jsx, src/styles/app.scss
Adding a "green" indicator.
Merge to epic.
=> HOCS-2695 : CCT workflow

server/lists/index.js
Change "hub" team wording to "acceptance" team.
=> HOCS-2586: FOI Acceptance Stage

docker/docker-compose.yml, docker/scripts/services.sh
Add missing config to get the case creator working in docker.
Also :
- Fixed postgres error
- Added a sleep, to aws_cli. Without the sleep, it gets run multiple times.
- Set images to main rather than latest
=> Hocs 2527 additional config case creator

server/lists/index.js
New endpoints for COMP CCT lists: business area, enquiry reason.
Merge to epic.
=> HOCS-2913 : CCT business area and enquiry reason

server/services/forms/index.js
Handle contributions from COMP case types.
Merge to epic.
=> HOCS-2711 : fix MC for COMP

server/lists/index.js
Replacing "NRO" with "Owning CSU".
Merge to epic.
=> HOCS-2999 : Add Owning CSU

server/lists/adapters/__tests__/__snapshots__/case-view-all-stages.spec.js.snap, server/lists/adapters/case-view-all-stages.js, src/shared/common/forms/__tests__/__snapshots__/mapped-display.spec.js.snap, src/shared/common/forms/__tests__/mapped-display.spec.js, src/shared/common/forms/mapped-display.jsx
Change the MappedDisplay component so that it renders checkboxes differently.
Instead of:    "MappedDisplay field: Send to QA"
Render as:    "Send to QA: <disabled checked checkbox>
=> HOCS-2977 - Fix rendering of checkboxes in MappedDisplay component.

server/lists/index.js, src/shared/common/components/workstack.jsx, src/styles/app.scss
New endpoint to return CCT Case Outcomes.
New workstack column, deadline "dateRAW" for Red-Amber-White highlighting.
Merge to epic.
=> HOCS-3076 : CCT requested changes

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap, server/lists/adapters/__tests__/workstacks.spec.js, server/lists/adapters/workstacks.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
Server side passes through the whole primary correspondent (full name and postcode).
Client side, new data adapter to pull data from primary correspondent by key.
Merge to epic.
=> HOCS-2847 : COMP search results

src/shared/common/components/workstack.jsx
Handle cases in search results without a primary correspondent.
Merge to epic.
=> HOCS-3126 : search results without a primary correspondent

src/shared/common/forms/composite/__tests__/__snapshots__/somu-list.spec.jsx.snap, src/shared/common/forms/composite/__tests__/somu-list.spec.jsx, src/shared/common/forms/composite/somu-list.jsx
Add a comp table as well as an MPAM table.
Allow different rendering for each table summary type.
=> HOCS-3123 - Add a Comp contributions table.

docker/keycloak/local-realm.json, server/lists/adapters/case-notes.js
Added new users to keycloak to allow the progression of FOI workflow. 
Caseworker 2 and Caseworker 3 are now both members of FOI BICSPI G6G7 Approval team 1 and 
FOI BICSPI SCS Approval Team.
=> HOCS-2570 add new users for FOI approval teams

server/services/__tests__/action.spec.js, src/shared/common/forms/__tests__/__snapshots__/confirmation-with-case-ref.spec.js.snap, src/shared/common/forms/__tests__/confirmation-with-case-ref.spec.js, src/shared/common/forms/__tests__/form-repository.spec.js, src/shared/common/forms/confirmation-with-case-ref.jsx, src/shared/common/forms/form-repository.jsx, src/shared/common/forms/form.jsx
* Create confirmation with case reference component
=> HOCS-2545 FOI Dispatch (MVP)

server/config.js, server/tenantConfig.js, src/shared/common/components/__tests__/__snapshots__/phase-banner.spec.js.snap, src/shared/common/components/__tests__/phase-banner.spec.js, src/shared/common/components/phase-banner.jsx
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-3079
=> HOCS-3079 Alter application banner when running in a NOTPROD environment

server/lists/index.js
Added a new list service for FOI specific topic list
=> HOCS-3251 add new foi list to server

src/shared/common/forms/__tests__/__snapshots__/review-field.spec.jsx.snap, src/shared/common/forms/__tests__/review-field.spec.jsx, src/shared/common/forms/back-button.jsx, src/shared/common/forms/form-repository.jsx, src/shared/common/forms/form.jsx, src/shared/common/forms/review-field.jsx, src/shared/pages/form-enabled.jsx, webpack.config.js
* Create summary component with Change link
=> HOCS-3287 Check your answers screen

server/lists/adapters/case-notes.js, server/lists/adapters/case-summary.js, server/lists/adapters/workstacks.js
This change re-applies a fix that was reverted inadvertently during a merge from comp to main.
=> HOCS-3008 : Re-apply stopForceFlush

server/services/forms/index.js
* move FOI contributions block to the correct json block
=> HOCS-3393 FOI Consider and Draft Stage - Unable to 'Add a Contribution'

server/libs/request.js
=> HOCS-3424 - Accept response compression.

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap, server/lists/adapters/__tests__/workstacks.spec.js
Added a composite cell of Case Ref and FOI Requester to a new column in the FOI workstack.
=> HOCS-3146 add FOI Requester to work stack

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap, server/lists/adapters/__tests__/case-notes.spec.js, server/lists/adapters/case-notes.js
* Add CORRESPONDENT_UPDATED type to case note renderer
=> HOCS-3525 - Case Timeline not updated when correspondent updated

server/lists/adapters/__tests__/workstacks.spec.js, server/lists/adapters/workstacks.js, src/shared/common/components/__tests__/workstack-tag.spec.jsx, src/shared/common/components/workstack-tag.jsx, src/shared/common/components/workstack.jsx
Adds support for displaying tags in workstack column data cells, to indicate particular statuses about a case clearly on a workstack view.
=> HOCS-3311 Workstack Tags

server/services/forms/schemas/approval-fulfillment-foi.js
Label correction made to approval fulfillment screen.
=> HOCS-3650 correct approval fulfillment label

server/lists/adapters/case-view-all-stages.js
Stop the accordion showing undefined next to the approval requests.
=> hocs 3641 fix approval accordion showing undefined

server/lists/adapters/workstacks.js, src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
A previous change added FOI_APPEAL to the contribution requested stages,
this changes this to be the correct value `FOI_APPROVAL`.
=> HOCS-3848: fix contribution requested stage

server/lists/index.js, server/middleware/__tests__/process.spec.js, server/middleware/__tests__/validation.spec.js, server/middleware/process.js, server/middleware/validation.js, src/shared/common/components/foi-actions.jsx, src/shared/common/forms/form-repository.jsx, src/shared/helpers/__tests__/show-condition-functions.spec.js, src/shared/helpers/show-condition-functions.js
* Make visibility functions more flexible
* Add new visibility functions to check value multiple fields
=> HOCS-3703 Ability to capture probate information

server/lists/adapters/statics.js, server/lists/adapters/workstacks.js, server/lists/index.js, server/middleware/__tests__/searchHandler.spec.js
Added a fix to display inactive team names with a tag indicating the team is deactivated.
=> HOCS-3397 add fix for missing team names

server/lists/adapters/actions/actionsSummaryAdapterFactory.js, server/lists/adapters/actions/externalInterestSummaryAdapter.js
=> HOCS-4175 Frontend is crashing when a case is loaded

server/services/forms/index.js
Enables adding of contribution requests for COMP2 cases
=> HOCS-4143 Contribution Requests for COMP2 cases

server/services/forms/index.js, server/services/forms/schemas/record-appeal.js
* Fix missing optionals for IR Review
=> HOCS-3884 - Add document upload to appeals

server/lists/index.js
=> HOCS-4136 - Draft response

server/lists/adapters/case-summary.js, src/shared/common/components/__tests__/__snapshots__/stage-summary.spec.jsx.snap, src/shared/common/components/__tests__/people.spec.jsx, src/shared/common/components/__tests__/stage-summary.spec.jsx, src/shared/common/components/people.jsx, src/shared/common/components/stage-summary.jsx
Added organisation field to show in people and case summary tabs.
=> HOCS-4345 add organisation field to show in people and summary tabs

server/lists/index.js
* Allow TO cases to be moved to a campaign
=> HOCS-4134 Campaigns

server/lists/adapters/__tests__/__snapshots__/case-view-all-stages.spec.js.snap, server/lists/adapters/__tests__/case-view-all-stages.spec.js, server/lists/adapters/case-view-all-stages.js
There is currently a check for undefined businessArea to stop an
undefined business area being displayed, this change adds another check
for an undefined business unit.
=> HOCS-3391: Remove undefined from COMP accordion

server/lists/index.js
Added stop list to treat Official workflow.
=> HOCS-4135 add stop list service

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/components/__tests__/workstack.spec.jsx, src/shared/common/components/workstack.jsx
Currently there are no checks in the DUE_DATE_WARNING renderer that
the due dates are in the past so they always display with the warning
class.
=> HOCS-3822: Add check that due date is in the past

server/lists/index.js
* Update Final Response documents list endpoint url
=> HOCS-4468 Additional Document Types for Treat Official

server/lists/index.js
Change S_TO_RECIPIENTS list to dynamic
=> HOCS-4515 change recipient list to dynamic

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap, server/lists/adapters/__tests__/case-notes.spec.js, server/lists/adapters/case-notes.js
External interest case note adapter supports multiple case types
=> HOCS-4542 Support multiple case types in case note adapter

server/lists/index.js
Adds interim letters case document list
=> HOCS-4631 Add Interim Letters document list

server/lists/index.js, src/shared/helpers/case-type-sidebar-tabs-flags.js
added capability for BF2 case officer to record interest.
=> HOCS-4398 BF2 add interest to action tab

server/services/forms/index.js, src/shared/common/forms/composite/somu-list.jsx
Add contribution support for POGR case type within the Investigation
screen.
=> HOCS-4634: add POGR contributions support

package-lock.json, package.json, server/middleware/file.js, server/middleware/request.js, server/services/forms/schemas/extend-deadline.js, server/services/forms/schemas/manage-people.js, server/tenantConfig.js
Bump UUID library to current latest version 8.3.2.
=> HOCS-4954: bump UUID to latest

.drone.yml, Dockerfile
Replaces npm install for npm ci in Dockerfile and pipeline
=> HOCS-4826 Replace npm install with npm ci

Dockerfile
14.18 has a few vulnerabilities.
=> Bump NodeJS version

server/lists/index.js
Addition of 3 static lists that are used within the POGR GRO ex-gratia
tab.
=> HOCS-4782: add GRO ex-gratia entity list 

server/lists/index.js
Add static lists for TO border force specific entity lists to be used
within field specific choices.
=> HOCS-5361: add static lists

server/config/searchFields/config.json
Add missing search fields for the POGR Stage 2 case type.
=> HOCS-5338: add POGR stage 2 search fields

.github/workflows/test.yml
=> Update test.yml node matrix

server/lists/index.js
Add three new static lists to support Ex-Gratia HMPO screen.
=> HOCS-5454: add new lists

server/lists/index.js
JIRA Link: https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5360
=> HOCS 5360 add TO BF enquiry lists

src/shared/common/forms/checkbox-grid.jsx, src/shared/common/forms/checkbox-group.jsx, src/shared/common/forms/radio-group.jsx
This changes frontend components so that when they have showLabel set to false the legend is rendered as hidden rather than blank
=> HOCS-5498: IEDET Complaint type screen changes

server/lists/adapters/case-view-unallocated.js
This change allows visibility conditions to be passed as a prop to mapped fields
=> HOCS-5536: Enable visibilityConditions on mapped fields

server/config/case-type/creation-document-tag.json
Adds missing initial document tag for WCS
=> HOCS-5693 Add missing initial document tag

server/services/forms/schemas/case-create.js, server/services/forms/schemas/document-add.js
Sentence case `Create Single Case` on all applicable forms.
=> HOCS-5638: sentence case form title

package-lock.json, package.json
Update lint-staged, serialize-javascript, and removes unused babel-core
=> Chore: update dependencies

package-lock.json
Updates ESLint, Webpack, govuk-frontend, aws-sdk, various babel, autoprefixer, core-js, sass
=> ⬆️ Update dependancies

server/lists/adapters/__tests__/__snapshots__/documents.spec.js.snap, server/lists/adapters/__tests__/documents.spec.js, server/lists/adapters/documents.js
Add the new document labels for `AWAITING_MALWARE_SCAN`, `FAILED_MALWARE_SCAN`, and `AWAITING_CONVERSION`. This change also brings the wording in line with hocs-docs.
=> HOCS-6401: Add new document labels

package-lock.json
=> Update browser-list/caniuse db, apply npm audit fix for post-css vuln

helm/hocs-frontend-wcs.yaml, helm/hocs-frontend.yaml
HOCS-6820: This PR is to update keycloak 22 realm url for DECS frontend.
=> HOCS-6820:Update keycloak 22 realm url in frontend

src/shared/pages/form-enabled.jsx
I believe that this is this issue:
https://stackoverflow.com/questions/37956513/react-router-reset-focus-on-route-change-accessibility
=> HOCS-5269: Fix focus issue

src/shared/common/forms/accordion.jsx
Add index # to section id, matching the pattern used for other ids within the section
=> [HOCS-6905] Add index to accordion section ids

helm/hocs-frontend-wcs.yaml, helm/hocs-frontend.yaml
Keycloak22 realm url changes added yaml file for dev enviornment.
=> Keycloak22 realm url changes added yaml file

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap, src/shared/common/forms/dropdown.jsx
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-4967
Updates:
- Label attribute added to dropdown return options.
- Ternary operator added to avoid bypass of required dropdown selections.
- Snapshot updated to allow test pass.
=> Label added - HTML checker passed
