src/shared/common/forms/__tests__/date.spec.js
src/shared/common/forms/date.jsx
src/shared/common/forms/form.jsx

This PR changes the client-side year validation from a fixed `2100` to `currentYear + 100`, on the off chance that our service is still being used in several decades.
We rename the `Date` component to `DateInput` because `Date` is already used for a somewhat important purpose that we would prefer not to clash with.

 Avoid Y2K in year validation

---

src/styles/app.scss

- Change overflow behaviour to only show scrollbars if overflowing
- Use same font sizing as .govuk-body

Improve .code style

---

server/middleware/stage.js
src/shared/common/forms/composite/__tests__/__snapshots__/entity-manager.spec.jsx.snap
src/shared/pages/__tests__/__snapshots__/dashboard.spec.jsx.snap
src/shared/pages/__tests__/__snapshots__/workstack.spec.jsx.snap

We don't need to pass the allocate request through the workflow service now that we understand the allocation behaviour more,
The workflow service immediately calls casework so we might as well go direct.

point allocate links to casework

---

docker/docker-compose.yml

Ports 8080:8081 are often already in use, so switched.
Default schema to 'workflow' rather than 'public'.
Set the flyway schema name.

Changes to 'workflow' docker yml following onboarding experience

---

server/middleware/csrf.js

* HOCS-1049-edge-csrf-issue change from httponly cookie
* HOCS-1049-edge-csrf-issue change csrf cookie path
* HOCS-1049-edge-csrf-issue increase cookie security
* HOCS-1049-edge-csrf-issue allow insecure cookie in dev

Bug/hocs 1049 edge csrf issue (#319)

---

server/lists/index.js

Display Casework team name instead of UUID on Case Details view. Merge to WCS.

HOCS-1331 : display casework team name

---

.drone.yml

Prior to this commit, Drone deployments would deploy to cs-dev, and,
once completed successfully, would deploy to wcs-dev.
This commit changes that behaviour so that cs-dev and wcs-dev are
deployed to simultaneously, in parallel.
This utilises the parallel execution step in Drone CI:
https://0-8-0.docs.drone.io/pipelines/#parallel-execution
This will save two minutes or so on each merge to master.

Deploy to dev environments in parallel

---

server/middleware/__tests__/searchHandler.spec.js
server/middleware/searchHandler.js

Updating the fetch logic for 'DEFAULT' workstack type, as it is not guaranteed to always be the first item in the list.

HOCS-1808 - Wcs search result page is always blank

---

server/services/action.js
src/shared/common/forms/__tests__/__snapshots__/panel.spec.js.snap
src/shared/common/forms/panel.jsx
src/shared/pages/form-enabled.jsx
src/styles/app.scss

- changed 'Created a new case' massage to 'Case Created'
- separated case link from success banner to make it more apparent it's a clickable link
- styled case ref button to make it look like an actual hyperlink
- removed 'Success' massage to match new design

HOCS-1730 - UKVI Change success page

---

docker/docker-compose.yml

The localstack image version has been set to `0.9.5`; this localstack services from this version are known to work with all the HOCS/WCS services, whereas a later localstack version broke the search functionality as the version of elasticsearch (from localstack) was not compatible with `hocs-search` service.

Set localstack image version so localstack services remain compatible.

---

src/styles/app.scss

Added css to prevent overflow as described in HOCS-1838. This css only targets the entity-list.jsx component.

HOCS-1838: Prevent entity-list.jsx table from overflowing.

---

server/lists/adapters/__tests__/__snapshots__/documents.spec.js.snap
server/lists/adapters/documents.js
src/shared/common/components/__tests__/__snapshots__/document-list.spec.jsx.snap
src/shared/common/components/document-list.jsx
src/shared/common/components/document-pane.jsx
src/shared/common/forms/composite/__tests__/__snapshots__/entity-manager.spec.jsx.snap
src/shared/common/forms/composite/entity-manager.jsx

- moved 'Manage Documents' link to top of the page (to match people's tab)
- stopped 'UPLOADED' document tag from showing (pending and failed status will still be visible)
- shifted label colum to be the first column
- added 'PRIMARY DRAFT' label on primary draft document

HOCS-1825 - Primary Draft Tag in document list

---

server/middleware/searchHandler.js

- mapped new search field, when checkbox is not selected we pass in 'undefined' as
we want all results to come back regardless of HomeSecInterest status

HOCS-1802 - Search by Home Secretary interest case

---

src/shared/common/forms/__tests__/__snapshots__/type-ahead.spec.js.snap
src/shared/common/forms/type-ahead.jsx
src/styles/app.scss

The way in which the Control component was being modified caused this bug. It seems the only reason for this was to style the control when an error occurs, so the style is compliant with Gov error styling. To fix I did three things:
1. Remove Control object modification.
2. Add error class directly to the component.
3. Only applied the style to the 1st nested div, because the div which the class is applied to has too much of `border-bottom` (because the `react-select` styling clashed with HOCS styling).

Fix for HOCS-1174: Topic search bar unresponsive after backspace

---

package-lock.json
package.json

The npm package manager has a built-in vulnerability checker that runs
when you install a new package. At the moment hocs-frontend is reporting
25,991 known vulnerabilities that should be patched (of which 3 are
"high").
This number is inflated. For example, one vulnerability is in lodash, a
JavaScript utility library that is consumed by many of our dependencies
(and dependencies of dependencies). A single vulnerability in lodash is
reported every time it appears in the node_modules tree, instead of once
per security advisory.
In this commit we run `npm audit fix` and commit the result. Most
installations of hocs-frontend will already be using the new
dependencies thanks to the caret ^ notation used for specifying
permitted dependency versions, which usually means the latest compatible …

HOCS-1870 Run `npm audit fix`

---

server/lists/index.js

- fetching users for case using new logic in CASEWORK,
in the background this looks up current stage team.

HOCS-1929 - Offline QA dropdown shows wrong team

---

server/tenantConfig.js
src/shared/layouts/components/__tests__/__snapshots__/footer.spec.js.snap
src/shared/layouts/components/__tests__/footer.spec.js
src/shared/layouts/components/footer.jsx

This commit enables the pre-existing Footer component to be shown on all
pages. Previously there was just a white box where the footer would
usually be.
We additionally create a `showOGL` property for the footer and default
it to disabled. This property determines whether the footer should have
the "All content is available under the Open Government Licence v3.0"
message. We disable it by default as it is misleading for internal
services.
We retain the (c) Crown Copyright and the coat of arms of the British
Government.
This commit also adds a new environment variable,
ACCESSIBILITY_STATEMENT_URL. If this variable is set, we show an
"Accessibility" link in the footer that links to that URL. If it's
disabled, we don't. It's set as an environment variable instead of
hardcoded into the …

HOCS-1867 Add footer, a11y statement to DECS

---

src/shared/common/forms/composite/entity-list.jsx

- added missing logic that picks up on 'primary' property of
choice object in entity list. When primary flag is present and set
to 'true' the selection is defaulted to that object.
Leaving the existing logic behind means that when no primary flag is set
the first item will still be selected as per old solution.

HOCS-1996 - UKVI - when a second correspondent

---

server/services/forms/schemas/manage-people.js
src/shared/common/forms/composite/__tests__/__snapshots__/entity-list.spec.jsx.snap
src/shared/common/forms/composite/__tests__/entity-list.spec.jsx
src/shared/common/forms/composite/entity-list.jsx

Entity list now accepts new property "hideRemovePrimary" to hide the remove link against the primary (initially selected) list item.

HOCS-1970 : hide the Remove link when primary correspondent

---

src/shared/layouts/components/__tests__/__snapshots__/header.spec.js.snap
src/shared/layouts/components/header.jsx

Prior to this commit, hocs-frontend failed WCAG 2.1 criterion 2.4.1
Bypass Blocks. This commit adds a skip link to the header, not visible
until focused, that allows users that navigate sequentially through
content more direct access to the primary content of the page.
This commit has implications for the DECS Accessibility Statement. When
this commit is merged to master, the accessibility statement should be
updated to remove references to failing WCAG 2.1 criterion 2.4.1.

HOCS-1980 Add skip link to header

---

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
src/shared/common/components/workstack.jsx

Previously we had an empty label element next to the big checkboxes in
workstack view. These labels were required to make the checkboxes render
properly. However, because the labels were empty, they didn't help
screen-readers to understand what the checkboxes were associated with.
This commit adds the case's reference (e.g. HOCS/12345/20) to the
contents of the label, and wraps it in a CSS class that hides it
visually (as it's only useful to screen-readers).
This now means that VoiceOver announces the case reference when you tab
into the associated checkbox, instead of having to tab to the next
column and back again.
This commit fixes an issue that is listed in the DECS accessibility
statement. When this commit gets deployed to production, the
accessibility statement should be updated to …

HOCS-1992 Add case ref to w'stack checkbox labels

---

server/lists/adapters/case-notes.js

Previously when looking at case notes in the timeline we showed the 12 hour clock. This could get unnecessarily confusing as a case note that is added at 7:31pm would just show 7:31 without the meridiem at the end, meaning the user could be confused as to whether this is AM/PM.
This update toggles the International Date Format to use 24 hour time so the previous example would show 19:31 instead of 7:31.

HOCS-2040: change to use 24 hour clock

---

src/shared/common/forms/__tests__/expandable-checkbox.spec.js
src/shared/common/forms/expandable-checkbox.jsx

When unchecking a already selected expandable checkbox, previously this would save undefined as the value. Due to this the front-end summary page and the audit extracts show this value as undefined. This is not anticipated behaviour. This change fixes this by saving empty as the value, thus, fixing the summary page and the audit extraction.

HOCS-2038: expandable checkbox no longer saves undefined

---

server/routes/dashboard.js

Move up the logging of the case reference to just after retrieving from the request for production issue. Then add further logging to capture encoded string.

HOCS-2096: add further logging

---

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
src/shared/common/components/__tests__/workstack.spec.jsx
src/shared/common/components/workstack.jsx

As a result of requested change by WCS, the capability to have multiple data_value_keys has been added. This allows the user to specify a data_value_key and if it is present it will show. If the key is not present it will then fallback to the next and so forth. 
Tests have been updated to resemble this new functionality.

HOCS-2004: Handle multiple data value keys for workstack

---

docker/scripts/services.sh

As a result of the elastic search index being moved to our private repo, we no longer have a need to instantiate with this empty file. General cleanup.

HOCS-1990: remove unnecessary ES file

---

src/styles/app.scss

We previously (HOCS-754) overrode the style of disabled fields to be
more consistent with the rest of DECS and the GOV.UK style.
However, the new styles failed WCAG 2.1 contrast ratios. The browser
style also seems to fail that standard, so this commit makes disabled
text fields -- which are only used in DECS to relay information to the
user about previously set fields they cannot change -- look more like
<p> or <dt> elements. This successfully conveys to the user the message
that these fields cannot be changed, while ensuring we comply with the
contrast ratio.
This commit has implications for the DECS accessibility statement, which
needs to be amended to remove references to the problem this commit
fixes.

HOCS-1897 Disabled fields have too low contrast

---

server/clients/index.js
server/config.js
server/lists/index.js
server/middleware/__tests__/standardLines.spec.js
server/middleware/standardLine.js
server/routes/api/index.js
server/routes/api/standardLines.js
server/tenantConfig.js
src/shared/contexts/application.jsx
src/shared/helpers/api-status.js
src/shared/layouts/components/header.jsx
src/shared/pages/__tests__/__snapshots__/snapshot.spec.jsx.snap
src/shared/pages/__tests__/snapshot.spec.jsx
src/shared/pages/standardLines/standardLinesReducer.js
src/shared/pages/standardLines/standardLinesView.jsx
src/shared/router/routes/index.js
src/styles/app.scss

This PR introduces the following things: 
- Adds the StandardLineScreen. This also includes all of the routing for the frontend to show the component.
- Adds a 'View Standard Lines' button to the header if the configuration is enabled to show this, that allows for the traversing to the page. 
- Add the routing to the backend server to allow for communication with the info service to retrieve the users standard lines.
- Adds the document client to the backend to allow for the downloading of the standard lines.
Tests have been added for all functionality.

HOCS-1853: add the Standard Lines page with routing

---

server/middleware/searchHandler.js

At present if a value is tokenized by elastic search to '1121' a search in the field '1121 ' will not return any results. In a normal system, values like this should be trimmed when searching, this in this case would trim to '1121' and therefore be matched by elastic search.

HOCS-2145: trim the correspondence reference number form value

---

server/services/form.js

The workflow service correctly returns a 401 when user changes reference type to a non-assigned team.
Front-end modified to propagate the error so that the dashboard is shown, not the case form.

HOCS-2015 UKVI Reference Type Change

---

server/middleware/__tests__/standardLines.spec.js
server/middleware/standardLine.js
server/routes/api/standardLines.js

As a result of misunderstanding of tickets, when on the view standard lines page, all of the standard lines should be returned regardless of whether they have access to a particular team. This pull request brings in this functionality. Alongside this, tests have been added to cover this new functionality.

HOCS-1853: return all standard lines

---

server/middleware/__tests__/validation.spec.js
server/middleware/validation.js
server/routes/dashboard.js
server/services/forms/schemas/dashboard-search.js

At present when searching by a case reference we check to see if the field contains '\b[a-zA-Z]{2,4}\/[0-9]{7}\/[0-9]{2}\b'. This regex checks the entire field text and passes if it contains the basic case reference pattern. This is not acceptable though as you can have anything else either next to it/ before it that would also pass, 'test MIN/0000000/00' would still be valid. This regex has been updated to enforce that the field matches exactly with the case reference pattern.
Alongside this we are currently not in line with what the error message style guide states we should return as incorrect input. Before we had improper english and used the word invalid. This commit changes this to inform the user they have to enter a case reference in the correct format.
At present we don't have …

HOCS-2163: Enforce stricter case reference regex

---

server/lists/index.js

At present the case types are loaded as a static list, this is an issue as we allow for topics to be added to teams through MUI. This change forced the list to be dynamic, which means that every time they are needed they are loaded in. This will allow new cases that are assigned to teams to show in the core application.

HOCS-2222: change the case type topics to dynamic

---

index.js
package-lock.json
package.json
src/styles/app.scss

note: The guidance I used to replace the old colours is here: https://frontend.design-system.service.gov.uk/migrating-from-legacy-products/#2-turn-off-compatibility-mode

HOCS-2226: Update govuk-frontend package from 2.9.0 to 3.10.0

---

.eslintrc.js
package-lock.json
server/lists/adapters/__tests__/__snapshots__/somu.spec.js.snap
server/lists/adapters/__tests__/somu.spec.js
server/lists/adapters/somu.js
server/lists/index.js
server/services/__tests__/form.spec.js
server/services/form.js
server/services/list/__tests__/service.spec.js
server/services/list/service.js
src/shared/common/forms/composite/__tests__/__snapshots__/somu-list.spec.jsx.snap
src/shared/common/forms/composite/__tests__/somu-list.spec.jsx
src/shared/common/forms/composite/somu-list.jsx
src/shared/common/forms/form-repository.jsx
src/shared/pages/form-enabled.jsx

This change adds the new somu list into the application, fully complete with all tests required. The somu list allows for a range of configuration highlighted below: 
- itemLinks (optional): add links to a new column in the table with a user specified action and label on a somu item
- primaryLink (optional): add a add link below the table that has a user specified action and label that impacts a somu type
- somuType (required): contains the following:
- choices (optional): pulls the list from the list service with the request parameters
- type (required): the type that the somu type links to (i.e. 'CONTRIBUTIONS')
- caseType (required): the case type the somu type links to (i.e. 'TEAM')

HOCS-2235: add ability to render somu list

---

server/libs/dateHelpers.js

When building we currently don't support ES6 exporting of functions. We are currently restricted to using module.exports.

HOCS-2259: change exporting

---

.drone.yml

Prior to this commit Drone was only building the Docker image on a push
to master. As tests are currently only run on Docker build, it means
that the automated tests aren't run until merge to master.
Worse, as pipelines are set up for this repository on push and
pull_request, GitHub will display a reassuring green checkmark shortly
after a PR is opened -- even though the PR has no meaningful tests run
on it.
This commit ensures that we build the image on every push event, and
therefore indirectly ensure that every pull request runs the test pack.

HOCS-2048 Build image on every push

---

server/lists/adapters/workstacks.js
server/middleware/__tests__/validation.spec.js
server/middleware/validation.js

This PR adds a requiredArray validator that allows for the checking that an inputted string can be parsed as an array and contains at least 1 item. Also improves the workstack display to only show information when at the required stage.

HOCS-2274: add validator and update workstack display

---

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap
server/lists/adapters/case-view-all-stages.js
server/lists/adapters/workstacks.js
server/services/forms/schemas/contribution-fulfillment.js
server/services/forms/schemas/contribution-request.js
src/shared/common/forms/composite/__tests__/somu-list.spec.jsx
src/shared/common/forms/composite/somu-list.jsx

At present in Multiple Contributions screens we have the idea of a businessUnit and businessArea. This change re-words this to be contributionBusinessArea and contributionBusinessUnit. Also fixes a missed edge case where data could be null in contributions.

HOCS-2199: update multiple contribution field names

---

server/lists/adapters/workstacks.js

This change is part of HOCS-2051 to allow UKVI users to filter by correspondent. This PR populates workstack display elements for correspondents
This should be merged in at the same time as the following PRs:
https://github.com/UKHomeOffice/hocs-frontend/pull/565
https://github.com/UKHomeOffice/hocs-data/pull/489
https://github.com/UKHomeOffice/hocs-casework/pull/367

HOCS-2051 ukvi search by correspondent results page

---

src/shared/common/components/document-pane.jsx
src/shared/helpers/__tests__/document-helpers.spec.js
src/shared/helpers/document-helpers.js

- Added logic to handle unexpected (or missing) response data from API call to hocs-docs preventing console errors.
- Separated `flattenDocuments`, `getFirstDocument` and `hasPendingDocuments` into their own helper class so they could be unit tested.
- Add unit tests for expected and unexpected values for those three functions.

HOCS-2285 Fix console errors when not running docs locally

---

server/services/forms/schemas/contribution-fulfillment.js

At a request from the business, remove the read-only aspect from the Contribution Fulfilment page. As a result of this, add the same validation from the contribution request page.

HOCS-2319: remove read only fields on Contribution Fulfilment

---

server/services/action.js

When updating the case contributions data value, previously we sent an JSON object with a value of data that contained the somu type items. This change to hocs-casework has regressed functionality. To fix this regression, this change sends the data as plain text, overriding the default 'application/json'.

HOCS-2309: change to send plain text in somu update data request

---

src/shared/common/forms/composite/__tests__/somu-list.spec.jsx
src/shared/common/forms/composite/somu-list.jsx
src/shared/pages/form-enabled.jsx

Due to a misunderstanding of the form-enabled submit handler, when a object array has been sent through it was not handling is correctly. This change reverts the somu change and ensures that the somu-list sends it through as a string instead of an object array.

HOCS-2316: Revert form-enabled somu change

---

src/shared/common/forms/__tests__/form-repository.spec.js
src/shared/common/forms/form-repository.jsx

As a result of the multiple contributions piece, we removed a field. Unfortunately previous cases rely on this field, this change allows us to enter a field and pass in a defaultValue that effects the actual value on the field.

HOCS-2325: Allow for defaultValue prop to propagate

---

src/shared/common/forms/form-repository.jsx

Change to the defaultDataAdapter to return the currentValue if one is not present in the data. 
This handles the edge case whereby the data[name] is empty and we don't want to override expected with defaultValues. 
At present no dataAdapters are passed through to the renderFormComponent, so there is nothing to worry about with this. 
Also removed console.log statements that shouldn't have been initially committed.

HOCS-2325: Change defaultDataAdapter to return currentValue

---

src/shared/common/components/__tests__/__snapshots__/workstack.spec.jsx.snap
src/shared/common/components/__tests__/workstack.spec.jsx
src/shared/common/components/workstack.jsx

Currently we check the contributionStatus on each of the core contribution items. This does not work as the contributionStatus is currently within a data object of the contribution item. This change changes the current check to use the data and ensures the data is there to stop undefined errors. Tests have been updated to ensure validity of action.

HOCS-2325: Change to use the data of contribution

---

server/services/forms/schemas/contribution-fulfillment.js
server/services/forms/schemas/contribution-request.js

As per the ticket add the is valid within date validator to the contribution received date. This therefore enforces that the date is within the last 180 days (unless changes through environment variable). This PR also cleans up the contribution fulfilment and contribution request screen by removing unnecessary validation messages.

HOCS-2313: contribution received date limit range

---

server/libs/__tests__/workstackColumnHelpers.spec.js
server/libs/workstackColumnHelpers.js
server/middleware/searchHandler.js

This bug fix should merged alongside: https://github.com/UKHomeOffice/hocs-data/pull/503
* Look for caseType specific search stack

HOCS-2353-MPAM-Correspondent-In-Workstack-Not-Search

---

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap
server/lists/adapters/__tests__/workstacks.spec.js
server/lists/adapters/workstacks.js
src/shared/common/components/workstack.jsx

This change populates the Correspondents/Case Reference column and adds a renderer for correspondentWithCaseLink

HOCS-2220-add mp and correspondents details to dcu workstack

---

src/shared/common/forms/__tests__/__snapshots__/radio-group.spec.js.snap
src/shared/common/forms/radio-group.jsx

The other input fields do not use aria labels, so for consistency:
* remove broken aria-describeby and rely on form label for screenreader description

HOCS-2395-Remove-broken-aria-reference

---

package-lock.json
package.json
src/shared/common/forms/__tests__/__snapshots__/date.spec.js.snap
src/shared/common/forms/__tests__/date.spec.js
src/shared/common/forms/date.jsx

CS-2403-Internal Bug: DateInput Component sets maxYear to current date + 100 years breaking tests every year
* mock date in tests so snapshot tests don't break
* modify component to evaluate date during creation, rather than on import

HOCS-2403-Mock date in tests

---

server/middleware/__tests__/validation.spec.js
server/middleware/validation.js

This PR fixes the validation error bug when both hideConditions & visibilityConditions have been defined on a field and in turn causes a conflict. Tests have also been written to cover the different scenarios.

HOCS-2465: Avoid hideConditions & visibilityConditions conflicts.

---

docker/README.md
docker/docker-compose.yml

This commit improves the Docker Compose experience for Frontend
somewhat, by adding documentation for Docker Compose, and making sure
that Docker brings the containers up in a sensible order (postgres
before info-service, for example; or Localstack before docs). I think
this has always been the intention with the Docker Compose file, as the
`depends_on` properties were already defined -- however, they only
waited for containers to *start*, and didn't wait for the containers to
be *ready* (which is now the new behaviour).
The feature this relies on was removed from Docker 3, but we're not
using any Docker 3 features so it's safe to drop it back down to Docker
2. (We're not using Docker Swarm, you see.) Any docker-compose version
devs are already using will still support this older version …

HOCS-2444 Add health-checks to Compose; add Readme

---

server/services/__tests__/form.spec.js
server/services/form.js

Currently for all non super users; to access a closed case we rely on receiving a 401 response from workflow service then we populate a read-only form. With the super user functionality (see HOCS-2027) a 401 response is not sent, and a form is returned with a null value, this fix generates the form exactly the same way as we do for non supers when accessing a closed case by populating the form using the `readOnlyCaseViewAdapter` adapter functionality.

HOCS-2472: MPAM super user cannot view closed cases

---

src/shared/common/components/workstack.jsx

* where a column entry is an object, stringify its values for filtering

HOCS-2477-Cannot-Filter-By-Correspondent-Or-Ref

---

server/services/forms/schemas/contribution-request.js

This PR changes the contributionDueDate validator to allow dates to be 6 months in the past.

HOCS-2473: Allow UKVI to mark overdue contribution as received

---

server/services/forms/schemas/contribution-fulfillment.js

The change in validation for the contribution-fulfillment form was missed in the last [PR](https://github.com/UKHomeOffice/hocs-frontend/pull/592/files). This PR adds the validator to this form.

HOCS-2473: Add isValidWithinDate validator to contribution-fulfillment.js

---

.dockerignore
.drone.yml
Dockerfile

This change implements the necessary changes to use Drone V1 as V0.8
is going to be deprecated. Changes include:
- Pull build, test out of Dockerfile into pipeline
- Removed pull request checks
- Changed to push to build_XXX instead of build-XXX
- Added commit sha tag
- Switched to using KUBE_TOKEN as defined in Drone rather than the kube
repo
- Added acyclic dependency graph for asynchronous build steps
- Made a QA release always release to both QA environments
consolidated build steps where possible

HOCS-2643: migrate from drone 0.8 to 1

---

server/middleware/__tests__/searchHandler.spec.js
server/middleware/searchHandler.js

Move the `signOffMinister` to the main section so we can differentiate it
and have custom logic for the `OverridePOTeamUUID`.

HOCS-2680: move sign off minister

---

docker/README.md
docker/docker-compose.yml

Adds required envvars for case creator and updates docker compose to use tags on images rather than pulling latest by default. Allows for running services depending on current workstream.

HOCS-2623 Update docker-compose for case creator

---

server/services/__tests__/action.spec.js
server/services/action.js
src/shared/common/forms/form-repository.jsx
src/shared/helpers/__tests__/hide-condition-functions.spec.js
src/shared/helpers/hide-condition-functions.js

Currently, we only support the hiding fields based on a data key and value. As we need to check more intricate details of individual contributions we need to have more control. This change adds afunction that can be called through the form repository that allowsfor checking if a contribution has an inner field of`contributionStatus`. To also allow for this the change has been implemented to support the passing of the data to secondary actions and be able to call a list of specified functions.

HOCS-2706: hide back button ability

---

.drone.yml

This adds a step to Drone that fires on push to the COMP epic branch,
which triggers a deployment to the hocs-delta environment.
Previously we were deploying manually to hocs-delta, and using a fixed
branch-based tag, which was causing inconsistencies and confusion. Here
we deploy a tag based on the Drone build number, which is easier to
track. If we wanted, we could deploy using the SHA hash for a similar
effect.

HOCS-2769 Autodeploy delta branch to delta env

---

server/services/forms/index.js
server/services/forms/schemas/add-correspondent-details.js
src/shared/common/forms/composite/__tests__/__snapshots__/entity-list.spec.jsx.snap
src/shared/common/forms/composite/__tests__/entity-list.spec.jsx
src/shared/common/forms/composite/entity-list.jsx

When creating a complaint, selecting wether the complaint is an MP is irrelevant.
This change modifies the correspondent creation to allow the skipping of the MP step.
This is achieved by passing 'addUrlPath' = 'addNoMp' when defining the entity-list field.

HOCS 2709 add without mp

---

server/lists/index.js

Currently, the teams endpoint is static and pulls the fresh list from
info on every pod start. As we now allow for dynamic teams to be
added through MUI this can cause discrepancies between data. This
change enforces that the team is pulled on every request.

HOCS-2674: change teams type

---

.drone.yml

This adds a step to Drone that fires on push to the FOI epic branch,
which triggers a deployment to the hocs-gamma environment.
Previously we were deploying manually to hocs-gamma, and using a fixed
branch-based tag, which was causing inconsistencies and confusion. Here
we deploy a tag based on the Drone build number, which is easier to
track. If we wanted, we could deploy using the SHA hash for a similar
effect.

HOCS-2885 Push FOI MVP to hocs-gamma automatically

---

server/lists/index.js

Issue identified with this change - as we rely on static team names 
within workstacks, summary tab and other places we cannot just 
remove the cache as the frontend no longer will display the names. A 
more thorough investigation of this cache removal needs to take 
place about unintended consequences. 
This reverts commit a3a4e05f17b46895544a29b99d78f9a8829920c0.

Revert "HOCS-2674: change teams type (#622)"

---

server/services/forms/index.js
server/services/forms/schemas/add-correspondent-details.js
src/shared/common/forms/composite/__tests__/__snapshots__/entity-list.spec.jsx.snap
src/shared/common/forms/composite/__tests__/entity-list.spec.jsx
src/shared/common/forms/composite/entity-list.jsx

Allow for add correspondent without a MP
addUrlPath defaults to "add"
Alternative addUrlPath = "addNoMp", which doesn't render MP question.
Ref: HOCS-2709

HOCS-2900  Hide the MP question when adding correspondents

---

server/lists/adapters/case-notes.js
server/lists/adapters/case-summary.js
server/lists/adapters/workstacks.js

Cache flushing was being triggered in various places and under
particular circumstances resulted in many flush requests being triggered unintentionally
in a very short space of time.
This change removes the force flush, so the cache clear will stick to the
cron schedule.

HOCS-3008 Prevent force flushing of cache

---

server/lists/adapters/users.js

HOCS-3077 fix frontend user issue
Currently the frontend pulls a list of users for each approal team at startup.
When this list is pulled, there is a comparison operator to check if each user
is the requesting user. At startup, however, there is no user, as it's not
triggered by a requested. This crashes the frontend.
* Only check the user matches the pulled user if one exists

Hocs 3077 fix frontend user issue

---

server/services/forms/index.js

"Case contributions" have been renamed to "Business contributions".
Merge to epic.

HOCS-3092 : "Add business contribution" link, fix

---

src/shared/common/forms/__tests__/form-repository.spec.js
src/shared/common/forms/form-repository.jsx

At present we always check to see if the component 'name' is within
the data and replace the value with that if it exists. In some
circumstances we don't want that to happen, this allows for a
`populateFromCaseData` prop type to be specified that bypasses
this and uses the defaultValue if specified or empty.
Restructuring this code into its own function to improve code
readability.

HOCS-2762: allow override for case data usage

---

server/middleware/__tests__/searchHandler.spec.js
server/middleware/searchHandler.js
server/services/forms/schemas/search.js

We have removed the OfficialEngagement from the search for MTS
cases and MTS cases going forward. As a result the business no
longer need to be able to search based off this and this can be
removed from passed data.

HOCS-2763: remove OfficialEngagement from search

---

server/lists/index.js

The draft upload stage is looking for the wrong document tag.
This PR updates the screen to look for the correct one.

HOCS-3148 Draft Document validation error

---

src/shared/common/forms/__tests__/__snapshots__/radio-group.spec.js.snap
src/shared/common/forms/__tests__/radio-group.spec.js
src/shared/common/forms/radio-group.jsx

At present there are instances whereby the choices have values that
contain characters that are not allowed in CSS selectors. This change
improves the id that the radio uses so that there is a reduced chance
of these characters being part of the selectors. We now use the
name of the character and the key index to identify each of the
options. Due to this change various tests need to be updated to use
this new id.

HOCS-3128: change radio control ids

---

.drone.yml

This commit exposes the ACPTUNNEL_IPS secret to the pipeline steps,
allowing us to let through traffic using those IPs to ingresses where
appropriate.
We also rename POISE_WHITELIST to POISE_IPs to more precisely describe
what is inside those secrets (a list of IP addresses), and match the
ACPTUNNEL_IPS wording.
Supported IP ranges for ACP are currently listed at:
https://docs.acp.homeoffice.gov.uk/support/ip-ranges/

HOCS-3100 Expose multiple IP range secrets

---

server/services/__tests__/action.spec.js
server/services/action.js

If at the end of a stage the user is a member of the team that handles the case at the next stage, then the case might want to be be allocated to them automatically and displayed on screen, instead of just going to the workstack.
When the workflow service - updateStageForward() - detects that the end of a stage is reached - in getStage() - it checks if the current user is on the team for the next stage. If they are the user is allocated to that case, and data relating to the new stage is returned to the front end.
The front end code detects if the stageId has changed, and uses that instead when it redirects.
The feature can be turned on by setting a process variable in the Camunda diagram.

HOCS-3193 Sticky Cases

---

server/config.js
server/models/error.js

At present to show stack traces within the error we rely on the
`isProduction` value in the config page. As turning this off in
non-local environments causes unintended consequences. To
mitigate this, a new `SHOW_STACKTRACE_ON_ERROR_PAGE` env
variable is being passed through. This is then used to signal whether
to pass through the stacktrace to the error model.

HOCS-3315: utilise show stack trace environment var

---

src/shared/common/components/workstack.jsx

Currently if only FOI is checked and a case with no correspondent exists, the frontend throws an error, this change adds a check to fix that.
* Check for empty objects passed to front end and turn them into empty strings

HOCS-3328 - Search Page not loading criteria options

---

server/lists/adapters/__tests__/workstacks.spec.js
server/lists/adapters/workstacks.js
server/lists/index.js
server/middleware/__tests__/searchHandler.spec.js

Deactivated team workstacks are appearing on the dashboard with blank labels. These labels are populated by the frontend from a list of teams from the info-service. Currently only the list of active teams is used, causing the issue.
* Use the full team list in the list service, including deactivated teams

HOCS-3397 Issues caused by team deactivation through Management UI

---

src/shared/common/components/workstack.jsx

fixed the sort function for primary correspondent to allow the Requester/Reference column to sort correctly on the FOI workstack.

HOCS-3474 update primary correspondent sort strategy

---

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap
server/lists/adapters/__tests__/workstacks.spec.js
server/lists/adapters/workstacks.js
server/lists/index.js

To support the new result set provided by the `/dashboard`
endpoint in casework, this change parses the result that will 
be returned. As we no longer need computation (as this is 
done in the backend service), we can simply just populate 
each of the cards.
This change also changes the list that is used when hitting 
the dashboard to `/dashboard` of casework.

HOCS-3013: change dashboard endpoint call

---

server/services/action.js
src/shared/common/forms/__tests__/__snapshots__/confirmation-with-team-name-and-case-ref.spec.js.snap
src/shared/common/forms/__tests__/confirmation-with-team-name-and-case-ref.spec.js
src/shared/common/forms/confirmation-with-team-name-and-case-ref.jsx
src/shared/common/forms/form-repository.jsx

Updates the allocation stage, removing the Request Type Selection screen, removing the Allocation Case Note entry field and adding in a confirmation screen displaying the team name and case number.

HOCS 3417 Allocate a case

---

src/shared/common/forms/__tests__/__snapshots__/confirmation-with-team-name-and-case-ref.spec.js.snap
src/shared/common/forms/__tests__/confirmation-with-team-name-and-case-ref.spec.js
src/shared/common/forms/confirmation-with-team-name-and-case-ref.jsx

1) Remove green "Case has been allocated to:..." panel from final screen in Allocation stage
2) Black text in screen shot to change from "Case FOI/xxxx... has been allocated to..." to "Case FOI/xxxx... will be allocated to..."
3) Green button to read "Confirm allocation"

HOCS-3262 Changes to final allocation screen

---

server/lists/adapters/__tests__/__snapshots__/case-notes.spec.js.snap
server/lists/adapters/__tests__/__snapshots__/case-summary.spec.js.snap
server/lists/adapters/__tests__/case-notes.spec.js
server/lists/adapters/__tests__/case-summary.spec.js
server/lists/adapters/case-notes.js
server/lists/adapters/case-summary.js
server/middleware/__tests__/process.spec.js
server/middleware/__tests__/validation.spec.js
server/middleware/process.js
server/middleware/validation.js
src/shared/common/components/case-notes.jsx
src/shared/common/forms/form-repository.jsx
src/shared/helpers/__tests__/show-condition-functions.spec.js
src/shared/helpers/hide-condition-functions.js
src/shared/helpers/show-condition-functions.js

To support the addition of a new Enquiry Reason the following changes have been applied:
- Case note titles have been added for case notes of type:  `ENQUIRY_REASON_EUNATIONAL_OTHERDETAILS`
Additional quality of life improvements have been made whilst working on this:
- Checkbox components that have multiple values now have a space after the comma to improve readability. This has involved a new reducer-esque functionality that can be easily expanded for other component types.
- Forms that have hidden fields (based on visibilityConditions and hideConditions) no longer have there value sent to be added to a cases case data.
- Visibility conditions now support functional checks that are specified in the `show-condition-functions.js` file.
- `show-condition-functions` and …

HOCS-3464: eu national enquiry reason

---

server/lists/adapters/case-notes.js
server/lists/adapters/case-summary.js
server/lists/adapters/workstacks.js

Cache flushing was being triggered in various places and under
particular circumstances resulted in many flush requests being triggered unintentionally
in a very short space of time.
This change removes the force flush, so the cache clear will stick to the
cron schedule.

HOCS-3008 Prevent force flushing of cache (#639)

---

src/shared/common/components/__tests__/people.spec.jsx
src/shared/common/components/people.jsx

As a result of now returning the correspondent display name as part of
the request. If it is present we should use it, otherwise just the type
should be shown. This change also moves the whole title 'generator' to
within a function.

HOCS-3645: add correspondent type display name

---

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap
server/lists/adapters/__tests__/workstacks.spec.js
server/lists/adapters/workstacks.js
server/lists/index.js
server/middleware/__tests__/workstack.spec.js
server/middleware/workstack.js

Modify the USER_WORKSTACK list to point to the new endpoint in casework.
This endpoint passes through the user uuid.
To utilise the new endpoint result from casework, this change adapts the
`userAdapter` to remove the unecessary filters. Alongside this an
improvement to the byCaseReference comparator to check if the value is
present.

HOCS-3670: user workstack simplification

---

src/shared/common/forms/__tests__/__snapshots__/type-ahead.spec.js.snap
src/shared/common/forms/type-ahead.jsx

Orphaned form label issue fixed by using the inputId attribute for the Select component, this results in the label defined on line 73 being properly associated with the input.

HOCS-2089 Adding label to text box

---

src/shared/common/forms/__tests__/__snapshots__/radio-group.spec.js.snap
src/shared/common/forms/__tests__/radio-group.spec.js
src/shared/common/forms/radio-group.jsx

Add the visible property option to the radio group component. This will
assist with feature flagging options without having the whole field
reverted.

HOCS-3814: add visible prop to radio group

---

server/lists/index.js
server/services/forms/schemas/search.js

- Add `CASE_TYPES_FOR_SEARCH' as a separate list for case types to be shown on search page. (Existing case types list is used on the 'Create Case' page which needs to remain as-is).
- Fetches this list as part of loading the search screen.

HOCS-3720: Add Complaints Stage 2 to search

---

server/lists/adapters/__tests__/__snapshots__/workstacks.spec.js.snap
server/lists/adapters/__tests__/workstacks.spec.js
server/lists/adapters/workstacks.js

Currently, when a there is not a dueContribution we show all MPAM cases
at the contribution received stages as they have a requested
contribution. This change improves this logic to check the status that
is passed back to ensure that it is 'Received' before it sets it to
that.

HOCS-3848: change workflow display logic

---

server/services/forms/schemas/decorators/__test__/form-decorations.spec.js
server/services/forms/schemas/decorators/form_decorations/schema-decorations.js
server/services/forms/schemas/update-correspondent-details-foi.js

Adds an Organisation field used in FOI requests, this field is stored in the Correspondent table.

HOCS-3730 add organisation field to correspondent

---

server/middleware/auth.js
server/middleware/document.js
server/models/error.js
server/services/__tests__/form.spec.js
server/services/form.js
server/services/list/__tests__/service.spec.js
server/services/list/service.js

When the service returns a 403 when requesting a list it currently
bubbles up as a 500. This is not ideal and we should return the actual
issue, a 403. This change implements this.
Alongside this, we have 2 errors: `PermissionError` and 
`AuthenticationError`. While `PermissionError` is accurate it should
represent what it actually is as a 401, a AuthenticationError. This 
change also  renames AuthenticationError to a ForbiddenError to 
represent a 403 and then renames PermissionError to 
AuthenticationError.

HOCS-4008: bubble up forbidden service exceptions

---

server/lists/adapters/__tests__/__snapshots__/case-view-all-stages.spec.js.snap
server/lists/adapters/__tests__/case-view-all-stages.spec.js
server/lists/adapters/case-view-all-stages.js
src/shared/common/forms/__tests__/__snapshots__/mapped-display.spec.js.snap
src/shared/common/forms/__tests__/mapped-display.spec.js
src/shared/common/forms/mapped-display.jsx

Checkboxes currently have the choice label shown on the frontend by
default for the unallocated view. This change supports the passing
through of the showLabel prop from the checkbox that drives if the field
label should be used or the choice label.

HOCS-4440: support checkbox labels

---

server/lists/adapters/case-view-all-stages.js

This change reverts a line removal whereby we pass through the
`conditionChoices` prop for mapped-display components within the read
only view. This is used further down the line to populate the value.

HOCS-4514: pass through conditionChoices

---

server/lists/adapters/workstacks.js
server/lists/index.js
server/middleware/workstack.js

Repoint the calls for `STAGE_WORKSTACK` & `WORKFLOW_WORKSTACK` to a
drilled team endpoint on casework. As we are filtering by teams in
casework the filter on team has been removed.

HOCS-4544: change the stage endpoint

---

.drone.yml

This commit correct an omission from the previous 4696 commit, deploy to dev using the tag not the sha.

Hocs-4696: replace deploy by SHA with TAG

---

server/lists/adapters/__tests__/__snapshots__/documents.spec.js.snap
server/lists/adapters/__tests__/documents.spec.js
server/lists/adapters/documents.js
src/shared/common/components/__tests__/__snapshots__/document-list.spec.jsx.snap
src/shared/common/components/__tests__/document-list.spec.jsx
src/shared/common/components/document-list.jsx
src/shared/common/components/document-pane.jsx
src/shared/helpers/__tests__/document-helpers.spec.js
src/shared/helpers/document-helpers.js

When we load the documents page - even if a PDF does not exist (not
PENDING) it requests the file. This change ensures that only when a PDF
link exists we request the preview of the first matching document.
Currently, the backend status code is added to the tags that are
appending to the user display. This means that documents that fail virus
scan have `FAILED_VIRUS` displayed to the user within tags.
This change converts the status to a human-readable display - for the
above example `FAILED_VIRUS` -> `Failed Virus Scan`.

HOCS-4682: doc viewer requests when PDF exists 

---

server/lists/index.js

Rename of the endpoint for the CASE_DOCUMENT_LIST_INTERIM_LETTERS to the
plural type of `Interim Letter`

HOCS-4775: rename document list

---

server/lists/adapters/__tests__/__snapshots__/documents.spec.js.snap
server/lists/adapters/__tests__/documents.spec.js
server/lists/adapters/documents.js

[].concat returns a new label and does not modify the existing arrays
that are merged. This change returns the value of the concat.

HOCS-4774: pass through labels to document

---

.drone.yml

We're currently deploying an explicit version of NodeJS, which will inevitably end up being older than we'd like. This PR  changes our pipeline to also test against the latest LTS release of NodeJS, so that when we update we're definitely sure it'll work.
Most of the time the two builds will be running against the same binary. I considered adding the latest-latest version of NodeJS (at time of writing, Node 18) but I think that added overhead to the build that we don't need to consider: we're not going to upgrade for a few years yet.
This has a "failure: ignore" step on the new pipeline for now, as the LTS version of NodeJS breaks our build. We'll remove it as part of the LTS upgrade work.

HOCS-4837 Add matrix to test against latest-LTS of NodeJS as well as prod version

---

server/lists/index.js

Add the Draft document list to the dynamic collection of lists that can
be called at runtime. This list is currently called through POGR to
return all documents with the `Draft` tag associated with it.

HOCS-4636: add Draft document list to index

---

server/middleware/__tests__/case.spec.js
server/middleware/case.js

On addition and updating of a case note the user can enter a string of
whitespace and this will be entered. This change prevents that by
trimming the entry of the whitespace. This ensures that only the
required text is entered into case notes and no extra whitespace. The
default empty message is shown to the user in this case.

HOCS-4921: trim case note contents

---

server/services/action.js
src/shared/common/forms/__tests__/__snapshots__/panel.spec.js.snap
src/shared/common/forms/panel.jsx
src/shared/pages/form-enabled.jsx

Multiple usages of the Panel for actions pass the title as the summary
which breaks the Accessibility guidelines. All actions that pass title
incorrectly have been changed.
Also, includes a change that if the summary is not present then the
`div` does not present as an empty element.

HOCS-2083: change usage of Panel

---

server/middleware/__tests__/process.spec.js
server/middleware/process.js

During field submission we don't want to pass-through `somu-list` or
`display` fields. Previously, this was set to 'type' but the payload
actually used 'component' for the field type so this never worked. This
change allows this to be used correctly.

HOCS-5184: correct field processing

---

server/middleware/form/__tests__/process.spec.js
server/middleware/form/__tests__/validation.spec.js
server/middleware/form/fieldHelper.js
server/middleware/form/process.js
server/middleware/form/validation.js
server/routes/action.js
server/routes/api/action.js
server/routes/api/case.js
server/routes/case.js
server/routes/dashboard.js
server/routes/search.js

This change reworks the processing to allow for validation rules to be
applied before the stripping of case non-acceptable field types.
This involves effectively merging the validation step into the field
processing as they are tightly coupled. This then allows for the removal
of the data properties before forms are submitted to casework.

HOCS-5184: rework field processing

---

kube/kd/deployment.yaml
server/__tests__/tenantConfig.spec.js
server/config/searchFields/__tests__/searchFields.spec.js
server/config/searchFields/config.json
server/config/searchFields/searchFields.js
server/config/tenant/config.json
server/config/tenant/tenantConfiguration.js
server/services/forms/schemas/search.js
server/tenantConfig.js

Creation of static tenant configuration in a JSON file. This allows for
changes without backend database changes being required to change
frontend UI toggles.
Creation of search field JSON configuration file. This allows for all UI
logic for various case types to reside within the frontend and be
easily changeable without relying on an info service configuration call.
The search field generation code has also been refactored to remove a
redundant call and be more readable.

HOCS-5274: search and profile configuration

---

server/config/tenant/config.json

Initially when WCS was created autoCreateAndAllocate was set to true.
This was subsequently disabled but not respected in this config file -
this change deactivates this for the tenant.

HOCS-5335: disable auto allocate

---

Dockerfile

The user with uid 1000 is in use, causing the build to fail as `adduser`
wasn't able to add a user that already exists.
This commit removes the adduser line and replaces the chmod lines with
ones that utilise the existing base image's user instead of trying to
create a new one like in the commit reverted by
14b2681ed4909d2f1fc8599271634dd8d810de8f.
This builds locally, although I haven't tried running it.

HOCS-5364 Use user from base image

---

server/middleware/__tests__/case.spec.js
server/middleware/case.js

When sending a casenote with a falsey value, the codepath calls next
with an error but does not return at that point, this means that after
completion of the response a request to casework happens with a invalid
casenote. This is causing exceptions to be thrown from casework as we
don't support empty case notes and also express router failures.
This change fixes this by returning the value of the next as to
terminate the function.

HOCS-4270: fix falsey casenote request

---

server/config/searchFields/config.json

Remove the POGR `ComplainantHORef` search field as not required for this
case type.

HOCS-5412: remove POGR search field

---

src/shared/common/components/tab-ex-gratia.jsx
src/shared/common/forms/form-embedded-wrapped.jsx

Improve the form embedded component to now handle its own state
representation of data, errors and submit handler (using action to
designate API endpoint).
This provided no functional difference to how the ex-gratia tab works at
face value.
This is blocked until #1067 and #1068 are merged as this build upon them.

HOCS-5363: form embedded cleanup

---

server/tenantConfig.js

The old one is unused and not monitored. The DECS Live Support inbox
might not be the right email address for feedback, but at least it's
got humans looking at it.

HOCS-2646 Point feedback link to new email address

---

server/services/forms/schemas/add-correspondent-details.js
server/services/forms/schemas/add-member-details.js
server/services/forms/schemas/decorators/__test__/form-decorations.spec.js
server/services/forms/schemas/decorators/form_decorations/schema-decorations.js
server/services/forms/schemas/update-correspondent-details-foi.js
server/services/forms/schemas/update-correspondent-details.js

Changed labels from Building and Street to Address line 1 and Address line 2
This is in line with the guidance from the GOV Design System:
https://design-system.service.gov.uk/patterns/addresses/

HOCS-1504 Updated labels on correspondent forms

---

package-lock.json
package.json

Updates Jest to 26.x to resolve:
- CVE-2020-7789 https://github.com/advisories/GHSA-5fw9-fq32-wv5p
- CVE-2021-20066 https://github.com/advisories/GHSA-f4c9-cqv8-9v98

Update Jest to 26.x

---

server/lists/index.js

Add new static list to be loaded at startup for the HMPO Locations
selection (`POGR_HMPO_LOCATIONS`).

HOCS-5453: add new static list

---

server/lists/index.js

Add the two static lists for new fields within the HMPO Dispatch screen:
- `POGR_HMPO_DOCUMENT_DAMAGE_TYPE`
- `POGR_HMPO_DOCUMENT_TYPE`

HOCS-5455: add static lists

---

server/libs/__tests__/objectHelpers.spec.js
server/libs/objectHelpers.js
server/lists/adapters/__tests__/__snapshots__/case-view-all-stages.spec.js.snap
server/lists/adapters/__tests__/case-view-all-stages.spec.js
server/lists/adapters/case-view-all-stages.js

Rework of the unallocated accordion to support showing `somu-list`s.
This works by first analyzing the component and if it is a `somu-list`
it gets the meta-data and then the case items for it. This populates the
custom choice behaviour and then composes the titles for each of the
items.
The data for this unallocated accordion is calculated first which is
then used to filter out fields from the accordion that do not have a
data mapping.

HOCS-5560: rework unallocated accordion

---

server/config/case-type/__tests__/case-type.spec.js
server/config/case-type/case-type.js
server/config/case-type/creation-document-tag.json
server/services/__tests__/action.spec.js
server/services/action.js

Rework the case creation document tag away from calling info service and
using the first value returned from the array to hold a config file.
This removes one of the calls to info service and makes it clear what
the tag is that should be used.

HOCS-5679: refactor case creation document tag

---

src/shared/common/components/__tests__/__snapshots__/phase-banner.spec.js.snap
src/shared/common/components/phase-banner.jsx

The non-production banner uses a hyphen (-) instead of a dash (–), which is incorrect grammatically and does not match the production banner, which uses an en dash.
This commit changes the hyphen in that banner to use an en dash, which is UK usage. Some sources say to use an em dash instead, but that appears limited to US English.

Use en dash instead of hyphen-minus in test banner

---

server/lists/index.js

HOCS-5652 : This PR defines HMPO list which would load them in index.js file. This is a new requirement as part of HOCS-6652 to separate HMPO and GRO business contribution areas.

HOCS-5652 - Add new POGR HMPO contribution business area list

---

server/config/searchFields/config.json

Change to search field checkbox label from `Include Active Only` to the consistently used `Include Active Cases only`.

HOCS-5840: change to search field label

---

server/lists/adapters/workstacks.js
server/lists/index.js

This copies the way that we get the display names of the campaigns from the simple names for the MPAM workstack for TO cases

HOCS-5312: Create TO UKVI workstack

---

server/middleware/__tests__/request.spec.js
server/middleware/request.js
server/middleware/stage.js
server/models/error.js
server/routes/api/index.js

When an error is thrown within the express middleware there were a lot of instances of logging the entire Axios object. This isn't useful, and ends up spamming our SIEM.
This change removes this instances and adds a axios error middleware that transposes this error into a `GenericError`.
This change also (partially?) fixes an `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client` exception that we we're having.

HOCS-2005: rework Axios error handling

---

server/middleware/form/__tests__/validation.spec.js
server/middleware/form/validation.js

Validation on contributions are currently trying to parse falsey values, this change ensures we only call `JSON.parse` on values that aren't falsey.
This change also simplifies the logic to default invalid and calculate for a true value.
Exceptions will not only be thrown if the format of the JSON is incorrect.

Correct contribution request validation

---

server/lists/adapters/__tests__/__snapshots__/case-view-unallocated.spec.js.snap
server/lists/adapters/case-view-unallocated.js

For unallocated views that have a `displayAsFields` configuration, some fields that have child fields aren't having data passed through due to the filter. This change defaults to passing back the entire data blob for this to alleviate this.

HOCS-5846: change unallocated data handling

---

src/shared/common/forms/__tests__/date.spec.js
src/shared/common/forms/date.jsx

Trim date input fields to remove errant spaces at the start and end of each input field.

HOCS-5947: trim date component inputs

---

src/shared/pages/workstack.jsx

The current use of FormData and `append` results in undefined values being passed with the value as string "undefined".
This is causing parsing errors within the Node server and further downstream as "undefined" is not valid JSON.
This change reworks this FormData propagation to strip out any underlying null/undefined.

HOCS-5615: rework Workstack form submission

---

server/middleware/form/validation.js

Improved wording of isValidDate warning message to bring more in line with GDS guidance: https://design-system.service.gov.uk/components/date-input/

HOCS-6171: Change date validation message

---

src/shared/common/forms/composite/__tests__/somu-list.spec.jsx
src/shared/common/forms/composite/somu-list.jsx

To allow information to be passed to the user before they interact with the component, this change adds a hint text property.

HOCS-6261: support hint text in somu-list

---

.github/dependabot.yml

The dependency is automatically bumped by a minor version daily for the entire aws-sdk. This causes unnecessary dependabot updates. This change stops this update type, although security fixes will override this.

Ignore AWS-SDK dependency updates

---

server/lists/adapters/case-summary.js
server/middleware/__tests__/document.spec.js
server/middleware/__tests__/searchHandler.spec.js
server/middleware/__tests__/standardLines.spec.js
server/middleware/__tests__/workstack.spec.js
server/middleware/action.js
server/middleware/case.js
server/middleware/document.js
server/middleware/report.js
server/middleware/searchHandler.js
server/middleware/somu.js
server/middleware/stage.js
server/middleware/standardLine.js
server/middleware/templates.js
server/middleware/workstack.js
server/routes/dashboard.js
server/services/action.js
server/services/forms/schemas/remove-correspondent.js
server/services/forms/schemas/remove-document.js
server/services/forms/schemas/remove-topic.js
server/services/forms/schemas/search.js
server/services/forms/schemas/update-correspondent-details-foi.js
server/services/forms/schemas/update-correspondent-details.js
server/services/list/service.js

When requesting to backend services, there are currently places where we don't propagate the request id down to use as a correlation id. This is causing the inability to trace most logs from the frontend downstream.
Alongside this, we aren't passing the request id into the logger resulting in instances were we cannot correlate even within the service.

Improve correlation ID use

---

server/middleware/__tests__/autoCreateAllocate.spec.js
server/middleware/action.js
server/middleware/auth.js
server/middleware/cacheControl.js
server/middleware/case-notes.js
server/middleware/case.js
server/middleware/dashboard.js
server/middleware/document.js
server/middleware/form/process.js
server/middleware/render.js
server/middleware/report.js
server/middleware/request.js
server/middleware/searchHandler.js
server/middleware/somu.js
server/middleware/standardLine.js
server/middleware/templates.js
server/middleware/workstack.js
server/routes/api/workstack.js
server/routes/dashboard.js
server/routes/index.js
server/routes/page.js
server/routes/search.js
server/services/form.js

General cleanup to add return to all `next` calls. In most instances this is not required. Edge cases can exist that leads to a snowballing effect, where a next is called after a request is returned, effectively causing an error in the frontend.

Add return to all `next` calls

---

src/shared/layouts/components/__tests__/__snapshots__/body.spec.js.snap
src/shared/layouts/components/__tests__/skip-link.spec.js
src/shared/layouts/components/body.jsx
src/shared/layouts/components/header.jsx
src/shared/layouts/components/skip-link.jsx

This change pulls out the skip-link into its own distinct class to better utilise React. This new class handles the scrolling to the `main-content` id if it exists. To enable tab indexes to work after the focus, a value of "-1" has been provided. This makes it so that programmatically it can be focused but not through a keyboard.
This change should also fix HOCS-2050.

HOCS-4931: improve skip link

---

server/middleware/stage.js
server/services/form.js

There are currently 5 different `GET_FORM` events within the frontend. This makes it difficult to trace the logs in investigations.

Make form events specific

---

server/services/form.js
server/services/list/service.js

There was a missing pass-through of the requestId causing an non-allowed undefined header to attempt to be sent.

Pass-through request id to functions

---

server/routes/search.js

There was a missing pass-through of the requestId causing an non-allowed undefined header to attempt to be sent.

Pass-through request id to function

---

server/config/caseTabs/config.json
server/lists/index.js
server/middleware/__tests__/allocate.spec.js
server/middleware/allocate.js
server/middleware/form/process.js
server/routes/api/case.js
src/shared/common/components/__tests__/side-bar.spec.jsx
src/shared/common/components/__tests__/tab-out-of-contact.spec.jsx
src/shared/common/components/side-bar.jsx
src/shared/common/components/tab-out-of-contact.jsx
src/shared/common/forms/__tests__/form-embedded-wrapped.spec.js
src/shared/common/forms/form-embedded-wrapped.jsx
src/shared/common/forms/form-repository.jsx
src/shared/helpers/__tests__/hide-condition-functions.spec.js
src/shared/helpers/hide-condition-functions.js
src/shared/pages/form-enabled.jsx
src/shared/pages/stage.jsx

Add the `Out of Contact` behaviour that acts as a case reallocation form within a tab. 
This change consists of:
- Prop drill the react router `history` object down to the individual tab. This allows for a redirection back after the change has been applied.
- Addition of the `hasAnyValue` to the hide condition functions.
- New static list applied for the Out of Contact team selection.
Included within this is a fix to the hide condition that previously was mis-checking the input against itself to run a method. This has now been altered to correctly check if the `hideConditionFunctions` class has the function.

HOCS-6597: add allocation tab support

---

server/middleware/__tests__/document.spec.js
server/middleware/document.js
server/routes/document.js

Previously we're using the casework service as a permission middleware and sending the entire document through this service. This results in high memory usage and utilisation through this service, exaggerating existing performance issues.
This change adds a permission specific check that doesn't passthrough the entire file. After this permission check passes, the document is then requested from the document service directly.

HOCS-6562: change document handling

---

server/middleware/form/__tests__/process.spec.js
server/middleware/form/process.js

Change the way that dates are handled in the process middleware. This now uses regex matching to retrieve the day, month, and year. These regexes ensure that if a non-alphanumeric character is found either side of the numbers, then the result of the regex is an empty value for the specific value. Each of the values allow for leading 0's however, these are then stripped from the result and then for day and month re-padded to length 2.

HOCS-6656: improve date handling

---

package-lock.json
package.json

- Force non-vulnerable semver version
- Only check production dependencies (all levels) and high severity for dev dependencies (to work around un-fixed word-wrap vuln)

Workaround security vulns causing build failures.

---

server/middleware/form/__tests__/process.spec.js
server/middleware/form/process.js

HOCS-6656: Currently there is an issue when the user enters special or invalid numeric
values in date, month or year field - validation happens in javascript but it replaces 
invalid entry as blank to save it to backend DB. 
For example - if the data field entered as 2023/-05-25 
then while saving payload date is saved as -05-25 rather throwing an error in the UI. 
Also when its parsed in work stack it fails with below error:
**Cannot deserialize value of type `java.time.LocalDate` from String \"2023/-05-25\": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2023/-05-25'**
Applied fix would contain if any of the date field is incorrect, the function would return an 
empty string and this will make sure the user will get an error requesting user to …

Hocs 6656 invalid date fix

---

src/shared/common/forms/radio-group.jsx
src/styles/app.scss

HOCS-6732: Introduce type divider which will be used in hocs-frontend 
to display divider. 
Respective changes added to workflow branch https://github.com/UKHomeOffice/hocs-workflow/compare/main...hocs-6732_divider_spike. 
Once dev pulls workfow & frontend for this branch, they should be able to see divider text as below screenshot.
However frontend PR needs to be merged.

HOCS:6732: New css to override divider and added div tag radio-group.jsx
